photos page, basic functionality
joseph-p-pasaoa/holding__WebApp pull request #22
Opened 2019-11-10 22:12 UTC by DouglasMacKrell

CSS will shape this whole thing up, but the reloads I've built into the code work great and don't cost us our parameters.

@joseph-p-pasaoa @KathyPuma @Bpmauge

2019-11-11 06:25 UTC, joseph-p-pasaoa requested changes

2019-11-11 06:25 UTC, joseph-p-pasaoa commented on client/js/photos.js
> +    let existingPhotos = response.data.body
if the album is empty, the browser breaks. you should put this part of the function (lines 12-27) into a condition: if (response.data.body) {}
response.data.body will be null if there are no photos in the album

2019-11-11 06:26 UTC, joseph-p-pasaoa commented on client/js/photos.js
> +    let existingPhotos = response.data.body
@DouglasMacKrell

2019-11-12 01:17 UTC, Briahana-Mauge approved these changes

2019-11-12 01:18 UTC, joseph-p-pasaoa approved these changes

2019-11-12 01:18 UTC, merged